(require 'skbd)

(skbd-global-mode)
(defun set-cmd-to-kbd (command keybinding)
  "Bind COMMAND to a KEYBINDING quickly."
  (interactive "sCommand: \nsKeybinding: ")
  (setq cmd command)
  (define-key skbd-mode-map (kbd keybinding) `(lambda ()
                                                (interactive)
                                                (let ((default-directory ,default-directory))
                                                  (compile ,cmd)))))
(define-key skbd-mode-map (kbd "M-x") 'helm-M-x)
(define-key skbd-mode-map (kbd "M-<up>") 'windmove-up)
(define-key skbd-mode-map (kbd "M-<down>") 'windmove-down)
(define-key skbd-mode-map (kbd "M-<left>") 'windmove-left)
(define-key skbd-mode-map (kbd "M-<right>") 'windmove-right)
(define-key skbd-mode-map (kbd "C-x C-b") 'ibuffer)
(define-key skbd-mode-map (kbd "C-+") 'text-scale-increase)
(define-key skbd-mode-map (kbd "C--") 'text-scale-decrease)
(define-key skbd-mode-map (kbd "C-x g") 'magit-status)
(define-key skbd-mode-map (kbd "C-c h") 'helm-custom)

(provide 'skbd-module)
