;; Custom modules
(require 'direx-module)
(require 'eshell-module)
(require 'helm-module)
(require 'js-module)
(require 'md-module)
(require 'notify-module)
(require 'php-module)
(require 'popwin-module)
(require 'powerline-module)
(require 'prelude-module)
(require 'python-module)
(require 'ruby-module)
(require 'skbd-module)
